# Generated by Django 2.2.5 on 2019-09-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=128)),
                ('client_name', models.CharField(max_length=128)),
                ('client_address', models.CharField(max_length=128)),
                ('client_website', models.CharField(max_length=128)),
                ('client_contact', models.CharField(max_length=128)),
                ('client_title', models.CharField(max_length=128)),
                ('client_phone', models.CharField(max_length=128)),
                ('client_email', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=128)),
                ('project_name', models.CharField(max_length=128)),
                ('project_category', models.CharField(max_length=128)),
                ('project_year', models.CharField(max_length=128)),
                ('project_groupname', models.CharField(max_length=128)),
                ('project_unit', models.CharField(max_length=128)),
                ('project_convenor', models.CharField(max_length=128)),
                ('project_supervisor', models.CharField(max_length=128)),
                ('project_teamleader', models.CharField(max_length=128)),
                ('project_groupsize', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='company',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='supervisors',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='proposals',
            name='client',
        ),
        migrations.RemoveField(
            model_name='proposals',
            name='proposal_incoming',
        ),
        migrations.RemoveField(
            model_name='proposals',
            name='supervisors',
        ),
        migrations.RemoveField(
            model_name='students',
            name='project',
        ),
        migrations.RemoveField(
            model_name='students',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Companies',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Proposals',
        ),
        migrations.DeleteModel(
            name='Proposals_Incoming',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Supervisors',
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
