# Generated by Django 2.2.5 on 2019-09-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20190923_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('proposal_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('proposal_name', models.CharField(max_length=128)),
                ('proposal_date', models.CharField(max_length=128)),
                ('proposal_unit', models.CharField(max_length=128)),
                ('proposal_note', models.CharField(max_length=128)),
            ],
        ),
    ]
