# Generated by Django 2.2.5 on 2019-10-23 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='client',
        ),
        migrations.AddField(
            model_name='proposal',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Contact'),
        ),
    ]
