# Generated by Django 2.2.5 on 2019-10-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='convenor',
            field=models.CharField(default='N/A', max_length=128),
        ),
    ]
