# Generated by Django 2.2.6 on 2019-10-16 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(default='', max_length=255)),
                ('website', models.CharField(default='', max_length=255)),
                ('desc', models.TextField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='external_supervisor',
            old_name='name',
            new_name='name_first',
        ),
        migrations.RenameField(
            model_name='internal_supervisor',
            old_name='name',
            new_name='name_first',
        ),
        migrations.RemoveField(
            model_name='external_supervisor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='external_supervisor',
            name='title',
        ),
        migrations.RemoveField(
            model_name='group',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='internal_supervisor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='internal_supervisor',
            name='title',
        ),
        migrations.AddField(
            model_name='external_supervisor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Department'),
        ),
        migrations.AddField(
            model_name='external_supervisor',
            name='name_last',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='incoming_proposal',
            name='company_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='internal_supervisor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Department'),
        ),
        migrations.AddField(
            model_name='internal_supervisor',
            name='name_last',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='group_members',
            field=models.ManyToManyField(related_name='members', through='CPPMS.Group', to='CPPMS.Student'),
        ),
    ]
