# Generated by Django 2.2.6 on 2019-10-25 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recieved_from_Client', models.CharField(choices=[('0', 'NO'), ('1', 'YES'), ('2', 'N/A')], default='2', max_length=1)),
                ('is_allocated_to_Unit', models.CharField(choices=[('0', 'NO'), ('1', 'YES'), ('2', 'N/A')], default='2', max_length=1)),
                ('is_allocated_to_Student_Team', models.CharField(choices=[('0', 'NO'), ('1', 'YES'), ('2', 'N/A')], default='2', max_length=1)),
                ('is_allocated_to_Supervisor', models.CharField(choices=[('0', 'NO'), ('1', 'YES'), ('2', 'N/A')], default='2', max_length=1)),
                ('is_generated_to_Project', models.CharField(choices=[('0', 'NO'), ('1', 'YES'), ('2', 'N/A')], default='2', max_length=1)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CPPMS.Proposal')),
            ],
        ),
    ]
