# Generated by Django 2.2.5 on 2019-09-25 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='group_code_canvas',
        ),
        migrations.RemoveField(
            model_name='student',
            name='project',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='num_students',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.IntegerField(default='0000'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='unit',
        ),
        migrations.AddField(
            model_name='student',
            name='unit',
            field=models.ManyToManyField(to='CPPMS.Unit'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_code_canvas', models.CharField(default='', max_length=255)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_leader', to='CPPMS.Student')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Project')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Student')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='group_members',
            field=models.ManyToManyField(through='CPPMS.Group', to='CPPMS.Student'),
        ),
    ]
