# Generated by Django 2.2.5 on 2019-10-02 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0002_project_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='leader',
        ),
        migrations.AddField(
            model_name='external_supervisor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Department'),
        ),
        migrations.AddField(
            model_name='incoming_proposal',
            name='company_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='internal_supervisor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='group_members',
            field=models.ManyToManyField(related_name='members', through='CPPMS.Group', to='CPPMS.Student'),
        ),
    ]
