# Generated by Django 2.2.5 on 2019-09-30 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0002_auto_20190925_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='supervisors_internal',
            new_name='internal_supervisor',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='date_modified',
            new_name='updated_at',
        ),
    ]
