# Generated by Django 2.2.5 on 2019-09-11 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0002_companies_contacts_departments_projects_proposals_proposals_incoming_students_supervisors_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Companies'),
        ),
        migrations.AddField(
            model_name='clients',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Contacts'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Departments'),
        ),
        migrations.AddField(
            model_name='departments',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Companies'),
        ),
        migrations.AddField(
            model_name='projects',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Proposals'),
        ),
        migrations.AddField(
            model_name='projects',
            name='supervisors',
            field=models.ManyToManyField(to='CPPMS.Supervisors'),
        ),
        migrations.AddField(
            model_name='projects',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Units'),
        ),
        migrations.AddField(
            model_name='proposals',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Clients'),
        ),
        migrations.AddField(
            model_name='proposals',
            name='proposal_incoming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Proposals_Incoming'),
        ),
        migrations.AddField(
            model_name='proposals',
            name='supervisors',
            field=models.ManyToManyField(to='CPPMS.Supervisors'),
        ),
        migrations.AddField(
            model_name='students',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Projects'),
        ),
        migrations.AddField(
            model_name='students',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Units'),
        ),
        migrations.AddField(
            model_name='units',
            name='supervisors',
            field=models.ManyToManyField(to='CPPMS.Supervisors'),
        ),
    ]
