# Generated by Django 2.2.5 on 2019-10-23 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0002_auto_20191023_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='CPPMS.Department'),
        ),
    ]
