# Generated by Django 2.2.6 on 2019-10-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0002_proposal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal_Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(default='', max_length=128)),
                ('status', models.CharField(choices=[('0', 'OPEN'), ('1', 'Pending'), ('2', 'Done'), ('3', 'N/A')], default='0', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
