# Generated by Django 2.2.5 on 2019-10-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0002_unit_convenor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='group',
            name='student',
        ),
        migrations.RemoveField(
            model_name='project',
            name='group_members',
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to='CPPMS.Student'),
        ),
    ]
