# Generated by Django 2.2.5 on 2019-10-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0002_project_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('filepath', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
