# Generated by Django 2.2.5 on 2019-09-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0003_auto_20190930_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='unit',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=128),
        ),
    ]
