# Generated by Django 2.2.5 on 2019-10-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0003_auto_20191012_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='external_supervisor',
            old_name='name_first',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='internal_supervisor',
            old_name='name_first',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='external_supervisor',
            name='name_last',
        ),
        migrations.RemoveField(
            model_name='internal_supervisor',
            name='name_last',
        ),
    ]
