# Generated by Django 2.2.5 on 2019-10-19 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0003_auto_20191019_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPPMS.Group'),
        ),
    ]
