# Generated by Django 2.2.6 on 2019-10-28 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0003_proposal_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal_stage',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CPPMS.Proposal'),
        ),
    ]
