# Generated by Django 2.2.5 on 2019-10-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0003_upload_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_proposal',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=20191006),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload_proposal',
            name='filepath',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
