# Generated by Django 2.2.5 on 2019-10-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0004_auto_20191019_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
