# Generated by Django 2.2.5 on 2019-10-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0004_auto_20191006_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_proposal',
            name='uploaded_at',
        ),
    ]
