# Generated by Django 2.2.5 on 2019-10-23 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0004_auto_20191023_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='CPPMS.Client'),
        ),
    ]
