# Generated by Django 2.2.5 on 2019-10-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0004_auto_20191012_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='external_supervisor',
            name='phone',
            field=models.CharField(default='00000000', max_length=10),
        ),
        migrations.AddField(
            model_name='external_supervisor',
            name='title',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='internal_supervisor',
            name='phone',
            field=models.CharField(default='00000000', max_length=10),
        ),
        migrations.AddField(
            model_name='internal_supervisor',
            name='title',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
