# Generated by Django 2.2.5 on 2019-09-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0005_auto_20190911_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals_incoming',
            name='company_desc',
            field=models.TextField(default='N/A'),
        ),
    ]
