# Generated by Django 2.2.5 on 2019-10-23 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0005_auto_20191023_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='CPPMS.Client'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='CPPMS.Contact'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='external_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='CPPMS.External_Supervisor'),
        ),
    ]
