# Generated by Django 2.2.5 on 2019-10-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0005_client_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
    ]
