# Generated by Django 2.2.5 on 2019-10-13 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMS', '0008_archive_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CPPMS.Proposal'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CPPMS.Client'),
        ),
    ]
